"""empty message

Revision ID: b9b4d5421983
Revises: 
Create Date: 2023-03-01 18:04:12.373122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b4d5421983'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('usuario', sa.String(length=60), nullable=False),
    sa.Column('contrasena', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('ruta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('punto_partida', sa.String(length=120), nullable=False),
    sa.Column('punto_llegada', sa.String(length=120), nullable=True),
    sa.Column('valoracion_usuario', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=60), nullable=True),
    sa.Column('temporalidad', sa.String(length=60), nullable=True),
    sa.Column('creador', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['creador'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('ruta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ruta_id'], ['ruta.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorito')
    op.drop_table('ruta')
    op.drop_table('usuario')
    # ### end Alembic commands ###
